apiVersion: schema.esdm.io/given-when-then/v1
kind: feature
name: get-todos
scope:
  domain: todos
  boundedContext: todos
  readModel: todos
scenarios:
  - name: should-show-all-todos
    given:
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 1
          title: a
          completed: true
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 2
          title: b
          completed: true
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 3
          title: c
          completed: false
    when:
      query: get-todos
      parameters:
        showing: ALL_TODOS
    then:
      result:
        todos:
          - id: 1
            title: a
            completed: true
          - id: 2
            title: b
            completed: true
          - id: 3
            title: c
            completed: false
        activeTodoCount: 1
        completedCount: 2
  - name: should-show-active-todos
    given:
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 1
          title: a
          completed: true
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 2
          title: b
          completed: true
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 3
          title: c
          completed: false
    when:
      query: get-todos
      parameters:
        showing: ACTIVE_TODOS
    then:
      result:
        todos:
          - id: 3
            title: c
            completed: false
        activeTodoCount: 1
        completedCount: 2
  - name: should-show-completed-todos
    given:
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 1
          title: a
          completed: true
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 2
          title: b
          completed: true
      - boundedContext: todos
        aggregate: todo
        event: added
        data:
          id: 3
          title: c
          completed: false
    when:
      query: get-todos
      parameters:
        showing: COMPLETED_TODOS
    then:
      result:
        todos:
          - id: 1
            title: a
            completed: true
          - id: 2
            title: b
            completed: true
        activeTodoCount: 1
        completedCount: 2
